services:
  ros:
    network_mode: host
    ipc: host
    privileged: true
    environment:
      ROS_LOCALHOST_ONLY: "0"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    volumes:
      - /dev:/dev