<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>g3gzsim</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="chesium@hotmail.com">chesium</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>xacro</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>g3g_frontier_exploration</exec_depend>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ros_gz_bridge</depend>
  <depend>ros_gz_image</depend>
  <depend>ros_gz_sim</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros GAZEBO_MODEL_PATH="${prefix}/models"/>
  </export>
</package>
